project_name: 【MC Aggregator】

env: 测试环境
# 测试人员名称，作用于自动生成代码的作者，以及发送通知的测试负责人
tester_name: Leo

app_host:
# 域名1
#host: http://localhost:9999
#host: https://test-backend.ethh.com
host: https://backend.ethh.com
# 后台管理域名2
#backend_host: http://localhost:9999
#backend_host: https://test-backend.ethh.com
backend_host: https://backend.ethh.com

# 用例执行类型 0: 冒烟测试(yaml文件未注明is_run=False的用例，默认都执行)、1: 日常巡检(yaml文件未注明is_run=True的用例，默认不执行)
execution_type: 1
#巡检是否需要每次发送统计结果
tg_inspection_results: error  # info: 无论失败或成功均发送用例执行结果、error: 失败才发送

# 实时更新用例内容，False时，已生成的代码不会在做变更
# 设置为True的时候，修改yaml文件的用例，代码中的内容会实时更新
real_time_update_test_cases: False

# 报告通知类型：0: 不发送通知 1：钉钉 2：企业微信通知 3、邮箱通知 4、飞书通知
notification_type: 0
# 收集失败的用例开关，整理成excel报告的形式，自动发送，目前只支持返送企业微信通知
excel_report: False

# 注意点：
# 之前为了小伙伴们拉下代码执行的时候不受影响，企业微信、钉钉、邮箱的通知配置的都是我的
# 我发现很多拉代码的小伙伴这里配置都没改，所有的通知都发到我这里来了哦~~麻烦看到这里的小伙伴自己改一下相关配置
# 钉钉相关配置
ding_talk:
  webhook: https://oapi.dingtalk.com/robot/send?access_token=2762af512313123
  secret: SEC613213123123825b3e27907ded9ed47fe7d5b17386d84580ab7848af52ec3
#  webhook:
#  secret:
# 数据库相关配置
mysql_db:
  # 数据库开关
  switch: False
  host:
  user: root
  password: '123456'
  port: 3306

# 镜像源
mirror_source: http://mirrors.aliyun.com/pypi/simple/

# 企业通知的相关配置
wechat:
  webhook:
#  webhook: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=22748687-fa3b-4e48-a5d7-0502cef422b4

### 邮箱必填，需要全部都配置好，程序运行失败时，会发送邮件通知!!!!
### 邮箱必填，需要全部都配置好，程序运行失败时，会发送邮件通知!!!!
### 邮箱必填，需要全部都配置好，程序运行失败时，会发送邮件通知!!!!
### 重要的事情说三遍
email:
  send_user: acztsfwyyx@163.com
  email_host: smtp.163.com
  # 自己到163邮箱中配置stamp_key
  stamp_key: WNbguxqwKqkuDm3u
  # 收件人改成自己的邮箱
  send_list: sunny393939zzz@gmail.com,wangmingbn@gmail.com
#  send_list: sunny393939zzz@gmail.com,wangmingbn@gmail.com,felix.deng@mcgrp.com,asutinhu@gmail.com

# 飞书通知
lark:
  webhook:

# telegram群通知
tg:
  token: 7600266569:AAE43aJLlGOE7BgA0HVeM03M0nX8dOXFz5A
  chat_id: "-4688426038"
  jenkins_skip_url: https://jenkins-stg.ethh.com/job/生产环境-接口自动化定时巡检

